---
ha_api_enabled: false
k8s_api_port: 6443
keepalived_package: keepalived
keepalived_service: keepalived
keepalived_config_path: /etc/keepalived/keepalived.conf
keepalived_virtual_router_id: 51
keepalived_auth_type: PASS
keepalived_base_priority: 150
keepalived_priority_step: 10
keepalived_advert_int: 1
