---
ingress_nginx_role_enabled: true
ingress_nginx_enabled: false
ingress_nginx_namespace: ingress-nginx
ingress_nginx_manifest_base_url: https://raw.githubusercontent.com/kubernetes/ingress-nginx
ingress_nginx_manifest_ref: controller-v1.11.3
ingress_nginx_manifest_path: deploy/static/provider/cloud/deploy.yaml
ingress_nginx_manifest_url: >-
  {{
    [
      ingress_nginx_manifest_base_url,
      ingress_nginx_manifest_ref,
      ingress_nginx_manifest_path
    ] | join('/')
  }}
kubeconfig_path: /etc/kubernetes/admin.conf
ingress_nginx_service_type: LoadBalancer
ingress_nginx_controller_service_name: ingress-nginx-controller
ingress_nginx_controller_deployment_name: ingress-nginx-controller
ingress_nginx_wait_timeout_seconds: 300
