[kube_control_plane]
k8s-cp-01 ansible_host=192.0.2.11

[kube_workers]
k8s-worker-01 ansible_host=192.0.2.21
k8s-worker-02 ansible_host=192.0.2.22

[lb_nodes]
# k8s-lb-01 ansible_host=192.0.2.10
# k8s-lb-02 ansible_host=192.0.2.9

[kube_cluster:children]
kube_control_plane
kube_workers
