---
validation_enabled: true
kubeconfig_path: /etc/kubernetes/admin.conf
validation_node_ready_timeout: 300s

validation_create_test_workload: false
# This deletes only the optional validation namespace created by this role.
# It has no effect unless validation_create_test_workload is also true.
validation_cleanup_test_workload: true
validation_test_namespace: k8s-validation
validation_test_app: validation-nginx
validation_test_image: nginx:stable-alpine
validation_test_replicas: 1
validation_clusterip_service_name: validation-nginx
validation_loadbalancer_service_name: validation-nginx-lb
validation_loadbalancer_timeout: 180

pod_security_admission_labels_enabled: false
pod_security_admission_namespaces: []
pod_security_admission_enforce: baseline
pod_security_admission_audit: restricted
pod_security_admission_warn: restricted
pod_security_admission_version: latest
